# This workflow checks whether the library is able to run without the std library (e.g., embedded).
# This entire file should be removed if this crate does not support no-std. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: device-driver-pregen-check
jobs:
  device-driver-pregen-check:
    runs-on: ubuntu-latest
    name: device-driver-pregen-check
    strategy:
      matrix:
        chip-rev: [r1, r3, r4, r5]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install device-driver-cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: device-driver-cli
      - name: Generate files
        run: device-driver-cli --manifest device_${{ matrix.chip-rev }}.yaml --device-name Device -o ci_gen_${{matrix.chip-rev}}.rs
      - name: Check that the files are the exact same
        uses: LouisBrunner/diff-action@v2.0.0
        with:
          old: ci_gen_${{matrix.chip-rev}}.rs
          new: src/versions/gen_${{matrix.chip-rev}}.rs
          mode: strict
          tolerance: same
